// Generated by convert_tflite_to_header.py
#ifndef MODEL_ESP32_H_
#define MODEL_ESP32_H_

extern const unsigned char model_esp32_tflite[] __attribute__((aligned(16)));
extern const unsigned int model_esp32_tflite_len;

#endif  // MODEL_ESP32_H_
